# Copyright 2020 Thomas Rogers
# SPDX-License-Identifier: Apache-2.0

OFF_MARKER_TAG = 3
ON_MARKER_TAG = 4
AXIS_MARKER_TAG = 5
TELEPORT_TARGET_TAG = 8

MARKER_TYPES = {OFF_MARKER_TAG, ON_MARKER_TAG, AXIS_MARKER_TAG, TELEPORT_TARGET_TAG}

MARKER_TILE_MAPPING = {
    OFF_MARKER_TAG: 2134,
    ON_MARKER_TAG: 2133,
    AXIS_MARKER_TAG: 2130,
    TELEPORT_TARGET_TAG: 0,
}

START_ID = 2
