# Copyright 2020 Thomas Rogers
# SPDX-License-Identifier: Apache-2.0

LOWER_LINK_TAG = 6
UPPER_LINK_TAG = 7

UPPER_WATER_TAG = 9
LOWER_WATER_TAG = 10

UPPER_STACK_TAG = 11
LOWER_STACK_TAG = 12

UPPER_GOO_TAG = 13
LOWER_GOO_TAG = 14

LOWER_LINK_TYPES = {LOWER_LINK_TAG, LOWER_WATER_TAG, LOWER_STACK_TAG, LOWER_GOO_TAG}
UPPER_LINK_TYPES = {UPPER_LINK_TAG, UPPER_WATER_TAG, UPPER_STACK_TAG, UPPER_GOO_TAG}

ROR_TYPE_LINK = 'Link'
ROR_TYPE_STACK = 'Stack'
ROR_TYPE_WATER = 'Water'
ROR_TYPE_GOO = 'Goo'

UPPER_TAG_MAPPING = {
    ROR_TYPE_LINK: UPPER_LINK_TAG,
    ROR_TYPE_STACK: UPPER_STACK_TAG,
    ROR_TYPE_WATER: UPPER_WATER_TAG,
    ROR_TYPE_GOO: UPPER_GOO_TAG,
}

LOWER_TAG_MAPPING = {
    ROR_TYPE_LINK: LOWER_LINK_TAG,
    ROR_TYPE_STACK: LOWER_STACK_TAG,
    ROR_TYPE_WATER: LOWER_WATER_TAG,
    ROR_TYPE_GOO: LOWER_GOO_TAG,
}

ROR_TILE_MAPPING = {
    ROR_TYPE_LINK: 504,
    ROR_TYPE_STACK: 504,
    ROR_TYPE_WATER: 2915,
    ROR_TYPE_GOO: 1120,
}

ROR_TYPES_WITH_WATER = {
    ROR_TYPE_WATER,
    ROR_TYPE_GOO,
}
