version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout

      - run:
          name: install python
          command: |
            Invoke-WebRequest https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile .\Miniconda3-latest-Windows-x86_64.exe
            start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=.\Miniconda3
            .\Miniconda3\Scripts\conda create --quiet --yes --name bloom python=3.6

      - run:
          name: install dependencies
          command: |
            .\Miniconda3\Scripts\conda activate bloom

            python -m pip install wheel
            python -m pip install -r requirements.txt
            
      - run:
          command: |
            .\Miniconda3\Scripts\conda activate bloom
            
            python setup.py bdist_apps
            python setup.py bdist_wheel
            copy version.txt dist\
          name: Build application
      - store_artifacts:
          path: dist     
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish-github-release:
    executor: python/default
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          command: |
            VERSION=$(cat ./artifacts/dist/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/dist/
          name: Create release    

workflows:
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

