version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: circleci/python:3.6.12
        environment:
          - ENV: CIRCLE
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            python3 -m pip install -r requirements.txt
      - python/save-cache
      - run:
          command: cd bloom && python3 setup.py bdist_apps
          name: Build application
      - store_artifacts:
          path: bloom/dist     
      - run:
          command: |
            VERSION=$(cd bloom && python3 setup.py --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} bloom/dist
          name: Create release    

workflows:
  main:
    jobs:
      - build-and-test

