version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout

      - run:
          name: download miniconda
          command: |
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe --output ./Miniconda3-latest-Windows-x86_64.exe
          shell: bash.exe

      - run:
          name: install miniconda
          command: |
            start-process -wait Miniconda3-latest-Windows-x86_64.exe -ArgumentList "/InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3"
          shell: powershell.exe

      - run:
          name: install python
          command: |
            ~/Miniconda3/Scripts/conda create --quiet --yes --name bloom python=3.6
          shell: bash.exe

      - run:
          name: install dependencies
          command: |
            set -eou pipefail

            ~/Miniconda3/Scripts/activate bloom

            python -m pip install wheel
            python -m pip install -r requirements.txt
          shell: bash.exe
            
      - run:
          command: |
            set -eou pipefail

            ~/Miniconda3/Scripts/activate bloom
            
            python setup.py bdist_apps
            python setup.py bdist_wheel
            copy version.txt dist\
          name: Build application
          shell: bash.exe
      - store_artifacts:
          path: dist     
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish-github-release:
    executor: python/default
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          command: |
            VERSION=$(cat ./artifacts/dist/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/dist/
          name: Create release    

workflows:
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
