version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build:
    executor: win/default
    environment:
      PYTHON: 3.6.4
    steps:
      - checkout

      - run:
          name: install python and create virtualenv
          command: |
            nuget install python -Version $env:PYTHON -ExcludeVersion -OutputDirectory .
            .\python\tools\python.exe -m pip install virtualenv
            .\python\tools\python.exe -m virtualenv env

      - run:
          name: install dependencies
          command: |
            env\Scripts\activate.ps1
            pip install -r requirements.txt
            
      - run:
          command: |
            env\Scripts\activate.ps1
            cd bloom && .\python\tools\python.exe setup.py bdist_apps && \
            cd bloom && .\python\tools\python.exe setup.py bdist_wheel && \
            cd bloom && .\python\tools\python.exe setup.py --version > dist/version.txt
          name: Build application
      - store_artifacts:
          path: bloom\dist     
      - persist_to_workspace:
          root: .
          paths:
            - bloom\dist
  publish-github-release:
    executor: python/default
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          command: |
            VERSION=$(cat ./artifacts/bloom/dist/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/bloom/dist/
          name: Create release    

workflows:
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

