version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: circleci/python:3.6.12
        environment:
          - ENV: CIRCLE
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            python3 -m pip install -r requirements.txt
      - python/save-cache
      - run:
          command: cd bloom && python setup.py bdist_apps
          name: Build application
      - store_artifacts:
          path: bloom/dist          

workflows:
  main:
    jobs:
      - build-and-test

