version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    docker:
      - image: circleci/python:3.6.12
        environment:
          - ENV: CIRCLE
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            python3 -m pip install -r requirements.txt
      - python/save-cache
      - run:
          command: |
            cd bloom && python3 setup.py bdist_apps
            cd bloom && python3 setup.py --version > dist/version.txt
          name: Build application
      - store_artifacts:
          path: bloom/dist     
      - persist_to_workspace:
          root: .
          paths:
            - bloom/dist
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
          name: Create release    

workflows:
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

